name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    with:
      number-of-agents: 3
      parallel-commands: |
        pnpm dlx nx-cloud record -- pnpm dlx format:check
      parallel-commands-on-agents: |
        pnpm dlx affected -t lint --parallel=3 & pnpm dlx affected -t test --parallel=3 --configuration=ci & pnpm dlx affected -t build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    with:
      number-of-agents: 3
